{
    "test_file": "Work_Environment/Create_Testing_in_Software_Development/test_python_software.py",
    "timestamp": "2024-09-02T10:00:44.209310",
    "status": "failure",
    "details": "============================= test session starts =============================\nplatform win32 -- Python 3.9.1, pytest-8.3.2, pluggy-1.5.0\nrootdir: C:\\Users\\ualer\\Downloads\\Saas do site\\A-I-O-R-G\nplugins: anyio-4.3.0, dash-2.14.2, Faker-22.4.0, json-report-1.5.0, metadata-3.1.1, typeguard-4.2.1\ncollected 0 items / 1 error\n\n=================================== ERRORS ====================================\n_ ERROR collecting Work_Environment/Create_Testing_in_Software_Development/test_python_software.py _\nImportError while importing test module 'C:\\Users\\ualer\\Downloads\\Saas do site\\A-I-O-R-G\\Work_Environment\\Create_Testing_in_Software_Development\\test_python_software.py'.\nHint: make sure your test modules/packages have valid Python names.\nTraceback:\n..\\..\\..\\AppData\\Local\\Programs\\Python\\Python39\\lib\\importlib\\__init__.py:127: in import_module\n    return _bootstrap._gcd_import(name[level:], package, level)\nWork_Environment\\Create_Testing_in_Software_Development\\test_python_software.py:4: in <module>\n    from Work_Environment.Create_Testing_in_Software_Development.python_software import download_vods, main\nE   ModuleNotFoundError: No module named 'Work_Environment'\n=========================== short test summary info ===========================\nERROR Work_Environment/Create_Testing_in_Software_Development/test_python_software.py\n!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!\n============================== 1 error in 1.20s ===============================\n"
}